### ISSUE TITLE
"Global Slack Bot Setting" is no where to be found in jenkins

### ISSUE THREAD

**Issue by ilyache** [tsszh/jenkins-slack-bot#1]
Hi, 

I know this isn't directly related with the code, but I've been trying to set this up and even though I've installed all of the needed plugins, I don't see the "Global Slack Bot Setting" that you've mentioned anywhere in my configure system screen. I do have however a "Global Slack Notifier Settings" but it doesn't show the fields you've mentioned in your documentation. 

Can you somehow assist me with this?

**Comment by tsszh** [comment]
Hi
I'm not sure how you install this plugin on your Jenkins server. Because I haven't release any prebuild package, the only way to test the program is to build the source codes by yourself and upload the "slack.hpi" file to the Jenkins server.

" I've installed all of the needed plugins". But actually, there are no other plugins that are required. Please don't install the [slack plugin](https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin) on Jenkins website.

I hope this would be helpful.

**Comment by ilyache** [comment]
Hi, 

Thanks for the reply, missed that part. I thought you were referring to the slack plugin available in Jenkins and not to the one you linked to. One last question - why did you write to not install the slack plugin from the Jenkins website? will that cause problems you're aware of?
